// ========== BLOCK 3: Prompts.swift - START ==========
//
//  Prompts.swift
//  Reflect: Creative Sparks
//
//  The curated prompt library — 200 prompts, each tagged with the
//  structural move(s) it embodies. See Docs/PROMPTS_FINAL.md for
//  the canonical source and Docs/AFM_SPEC.md for the move grammar.
//
//  This is the backbone of the experience. On capable devices, AFM
//  extends this set with generated prompts in the same grammar; on
//  every other device, this is the complete experience.
//

import Foundation

let curatedPrompts: [PromptCard] = [

    // MARK: - Subtraction [Move 1]
    PromptCard("Take one part away", .subtraction),
    PromptCard("Strip it down", .subtraction),
    PromptCard("Use fewer elements", .subtraction),
    PromptCard("Remove the expected", .subtraction),
    PromptCard("Find the quietest version", .subtraction),
    PromptCard("Simple subtraction", .subtraction),
    PromptCard("Only one element of each kind", .subtraction),
    PromptCard("What disappears when you remove the obvious?", .subtraction),
    PromptCard("Reduce until it breaks", .subtraction),
    PromptCard("What's left when you take everything away?", .subtraction),

    // MARK: - Inversion [Move 2]
    PromptCard("Turn it upside down", .inversion),
    PromptCard("Tell it backward", .inversion),
    PromptCard("Reverse it", .inversion),
    PromptCard("Tell the opposite story", .inversion),
    PromptCard("What if the opposite were true?", .inversion),
    PromptCard("Make it boring on purpose", .inversion),
    PromptCard("Find the worst version", .inversion),
    PromptCard("Tell the emotional lie", .inversion),
    PromptCard("Abandon your plan", .inversion),
    PromptCard("Stick to the plan", .inversion),

    // MARK: - Constraint [Move 3]
    PromptCard("Use a limitation", .constraint),
    PromptCard("Use the wrong tool", .constraint),
    PromptCard("Use no words", .constraint),
    PromptCard("Limit the tools", .constraint),
    PromptCard("Use only questions", .constraint),
    PromptCard("Use only statements", .constraint),
    PromptCard("Add a rule", .constraint),
    PromptCard("Use an unexpected material", .constraint),
    PromptCard("Use a cliché", .constraint),
    PromptCard("Break your favorite rule", .constraint),
    PromptCard("Make it for a stranger", .constraint),
    PromptCard("Use only what's already here", .constraint),

    // MARK: - Displacement [Move 4]
    PromptCard("Imagine it in another medium", .displacement),
    PromptCard("Change the time period", .displacement),
    PromptCard("Change the location", .displacement),
    PromptCard("Change the genre", .displacement),
    PromptCard("Change the tone", .displacement),
    PromptCard("Change the format", .displacement),
    PromptCard("Give it a soundtrack", .displacement),
    PromptCard("Draw it instead", .displacement),
    PromptCard("Make it mechanical", .displacement),
    PromptCard("Make it fictional", .displacement),
    PromptCard("Tell it with a symbol", .displacement),
    PromptCard("Tell it with color", .displacement),
    PromptCard("Make it a riddle", .displacement),
    PromptCard("Make it a protest", .displacement),

    // MARK: - Attention [Move 5]
    PromptCard("Notice what you're avoiding", .attention),
    PromptCard("What's too obvious?", .attention),
    PromptCard("Where is the tension?", .attention),
    PromptCard("What would an expert ignore?", .attention),
    PromptCard("Where is it rigid?", .attention),
    PromptCard("Find the contradiction", .attention),
    PromptCard("What is its shadow?", .attention),
    PromptCard("Trace the unseen lines", .attention),
    PromptCard("What's hiding in plain sight?", .attention),
    PromptCard("What is the question behind the question?", .attention),
    PromptCard("Listen to the hum beneath the noise", .attention),
    PromptCard("Honor what you've been dismissing", .attention),
    PromptCard("Notice what you always overlook", .attention),
    PromptCard("Where does the light get trapped?", .attention),
    PromptCard("What knowledge lives in your body?", .attention),

    // MARK: - Acceptance [Move 6]
    PromptCard("Make it feel accidental", .acceptance),
    PromptCard("Ruin it a little", .acceptance),
    PromptCard("Start with a mistake", .acceptance),
    PromptCard("Consider the wisdom in your mistakes", .acceptance),
    PromptCard("Find the pattern beneath chaos", .acceptance),
    PromptCard("Allow it to be unfinished", .acceptance),
    PromptCard("Make friends with emptiness", .acceptance),
    PromptCard("What remains when everything changes?", .acceptance),
    PromptCard("Find beauty in contradiction", .acceptance),
    PromptCard("Make it broken", .acceptance),
    PromptCard("Find beauty in what repels you", .acceptance),

    // MARK: - Perspective [Move 7]
    PromptCard("See it through someone else's eyes", .perspective),
    PromptCard("What would a child say?", .perspective),
    PromptCard("What would nature do?", .perspective),
    PromptCard("Inhabit someone else's certainty", .perspective),
    PromptCard("Make yourself a stranger", .perspective),
    PromptCard("What would your closest friend do?", .perspective),
    PromptCard("Who would disapprove?", .perspective),
    PromptCard("Who else is affected?", .perspective),
    PromptCard("What would the work say about you?", .perspective),

    // MARK: - Time [Move 8]
    PromptCard("Start with an ending", .time),
    PromptCard("Start with a sound", .time),
    PromptCard("Start with a fear", .time),
    PromptCard("Make it ephemeral", .time),
    PromptCard("Make it fragile", .time),
    PromptCard("What's its history?", .time),
    PromptCard("What's its future?", .time),
    PromptCard("Describe a memory you don't have", .time),
    PromptCard("Unravel a memory backward", .time),
    PromptCard("Walk backward into the future", .time),
    PromptCard("What exists before the beginning?", .time),
    PromptCard("Describe the echo of something that never happened", .time),
    PromptCard("Remember something that never happened", .time),
    PromptCard("Return to what you've abandoned", .time),
    PromptCard("Rewrite your history from a different perspective", .time),

    // MARK: - Reduction [Move 9]
    PromptCard("Make one thing", .reduction),
    PromptCard("Find the irreducible part", .reduction),
    PromptCard("Not the whole — just one brick", .reduction),
    PromptCard("What is the smallest true version?", .reduction),
    PromptCard("Do one thing completely", .reduction),
    PromptCard("Find the atom of it", .reduction),
    PromptCard("What is the single most important element?", .reduction),
    PromptCard("Make it fit in one sentence", .reduction),
    PromptCard("Reduce until it's only itself", .reduction),
    PromptCard("Name the one thing that cannot be removed", .reduction),

    // MARK: - Courage [Move 10]
    PromptCard("Try the impossible", .courage),
    PromptCard("Ignore logic", .courage),
    PromptCard("Give way to your worst impulse", .courage),
    PromptCard("Make it brutal", .courage),
    PromptCard("Make it shout", .courage),
    PromptCard("Destroy something", .courage),
    PromptCard("Resurrect something", .courage),
    PromptCard("Break your routine", .courage),
    PromptCard("Make art for no one", .courage),
    PromptCard("Go to the extreme", .courage),
    PromptCard("Do the thing you keep not doing", .courage),
    PromptCard("What if failure is the path?", .courage),
    PromptCard("What would you create if you couldn't fail?", .courage),
    PromptCard("Speak your desire without editing", .courage),

    // MARK: - Process [Move 11]
    PromptCard("Just carry on", .process),
    PromptCard("Make it feel inevitable", .process),
    PromptCard("Build a bridge to nowhere", .process),
    PromptCard("Follow the idea that won't leave you alone", .process),
    PromptCard("Once you begin, something will be found", .process),
    PromptCard("Let the work lead", .process),
    PromptCard("Make something — then see what it is", .process),
    PromptCard("Don't wait for permission", .process),
    PromptCard("The next step is enough", .process),
    PromptCard("Begin before you're ready", .process),
    PromptCard("Follow what feels alive, not what feels correct", .process),
    PromptCard("Let the broken pieces rearrange themselves", .process, .acceptance),
    PromptCard("Trust the process, not the plan", .process),
    PromptCard("Motion is the method", .process),

    // MARK: - Reality Check [Move 12]
    PromptCard("What are you actually making?", .realityCheck),
    PromptCard("Is it finished?", .realityCheck),
    PromptCard("What rules are you following?", .realityCheck),
    PromptCard("What are you avoiding?", .realityCheck),
    PromptCard("State the problem as simply as possible", .realityCheck),
    PromptCard("What is actually here?", .realityCheck),
    PromptCard("What would happen if you said yes?", .realityCheck),
    PromptCard("What's the real question?", .realityCheck),
    PromptCard("Look at what you've made. What is it?", .realityCheck),
    PromptCard("Name the feeling", .realityCheck),
    PromptCard("What are you really doing right now?", .realityCheck),

    // MARK: - Mixed — prompts that combine two moves
    PromptCard("Make it strange", .subtraction, .inversion),
    PromptCard("What if gravity reversed for a moment?", .inversion, .time),
    PromptCard("The shape of a secret", .displacement, .attention),
    PromptCard("The sound of a melting clock", .displacement, .time),
    PromptCard("What does silence taste like?", .displacement, .attention),
    PromptCard("Sketch the architecture of a feeling", .displacement, .reduction),
    PromptCard("Make it tactile", .displacement, .subtraction),
    PromptCard("Find the edge", .attention, .reduction),
    PromptCard("Find the center", .attention, .reduction),
    PromptCard("Explore what defies language", .displacement, .realityCheck),
    PromptCard("What lives in the echo?", .attention, .time),
    PromptCard("Walk the boundary between worlds", .perspective, .displacement),
    PromptCard("Invite absurdity into your logic", .constraint, .acceptance),
    PromptCard("Transform a wound into a doorway", .acceptance, .process),
    PromptCard("Let the shadows guide you", .perspective, .process),
    PromptCard("Whisper to the forgotten corners", .attention, .time),
    PromptCard("Make the invisible tangible", .subtraction, .displacement),
    PromptCard("Navigate by feeling rather than sight", .perspective, .process),
    PromptCard("What happens when you pause?", .realityCheck, .time),
    PromptCard("Find the hidden door", .process, .attention),
    PromptCard("Become the obstacle", .perspective, .acceptance),
    PromptCard("Meet your own resistance", .realityCheck, .acceptance),
    PromptCard("What if there is no problem to solve?", .realityCheck, .acceptance),
    PromptCard("Build something that cannot be finished", .reduction, .acceptance),
    PromptCard("Ask the question you keep not asking", .realityCheck, .courage),
    PromptCard("Describe the texture of time", .displacement, .time),
    PromptCard("Make it about the process", .process, .realityCheck),
    PromptCard("Dissolve the boundary between you and not-you", .perspective, .acceptance),
    PromptCard("Consider the lives of inanimate objects", .perspective, .attention),
    PromptCard("Speak in colors instead of words", .displacement, .subtraction),
    PromptCard("Let the peripheral become central", .attention, .inversion),
    PromptCard("Draw the shape of it", .displacement, .reduction),
    PromptCard("Where does it breathe?", .attention, .reduction),
    PromptCard("Find the extraordinary in the mundane", .attention, .acceptance),
    PromptCard("What is the weight of a word?", .attention, .reduction),
    PromptCard("Listen with your fingertips", .perspective, .attention),
    PromptCard("Only use logic", .constraint, .realityCheck),
    PromptCard("The color of forgetting", .displacement, .time),
    PromptCard("Make it for someone who will never see it", .constraint, .perspective),
    PromptCard("Begin at the end", .inversion, .time),
    PromptCard("What would the work say if it could speak?", .perspective, .realityCheck),
    PromptCard("Add something that doesn't belong", .constraint, .inversion),
    PromptCard("What's the tension between what it is and what it could be?", .realityCheck, .attention),
    PromptCard("Name what you're not naming", .realityCheck, .attention),
    PromptCard("Do one thing, completely", .reduction, .process),
    PromptCard("Where does the wind go when it stops?", .attention, .time),
]
// ========== BLOCK 3: Prompts.swift - END ==========
